spring.application.name=AI-TaskManager
# spring.data.mongodb.uri=mongodb://root:root&localhost:27017/TaskManager
server.port=8081

# when running in dockercompose use mongodb image not localhost
spring.data.mongodb.uri=mongodb://root:root@mongodb:27017/TaskManager?authSource=admin